---
title: "Bipolar Disorder"
format:
  revealjs:
    incremental: true
    theme: moon
    transition: slide
editor: visual
execute:
  echo: false

---


## Bipolar Disorder

According to the National Institute of Mental Health bipolar disorder (formerly called manic-depressive illness or manic depression) is a mental illness that causes unusual shifts in a person’s mood, energy, activity levels, and concentration.


## Three Types of Bipolar

There are three types of bipolar disorder. All three types involve clear changes in mood, energy, and activity levels

Bipolar I

Bipolar II

Cyclothymic Disorder

Age of onset is late adolescence to young adulthood.

## Depressive Symptoms and Manic Symptoms

MANIC Symptoms

Racing thoughts
Feeling able to do many things at once without getting tired
Having excessive appetite for food, drinking, sex, or other pleasurable activities

DEPRESSIVE SYMPTOMS

Having trouble concentrating or making decisions
Having a lack of interest in almost all activities
Feeling unable to do even simple things



## Treatments

Pharmacological treatments include lithium, anticonvulsants, antidepressants, antipsychotics.

Psychotherapy.

## Three Journal Articles

Emotion Dynamics Concurrently and Prospectively Predict Mood Psychopathology


## References

