---
title: "Does RSA Moderate Intergenerational Transmission of Aggressive Behavior? Replicating Raine, Choy, Auchenbach et. al (2023)"
format:
  revealjs:
    theme: simple
    transition: slide
editor: visual
execute:
  echo: false
---

## Abstract

RSA as a physiological index of PNS cardiac control, as a measure of emotion dysregulation (Beauchaine, T. P. 2015)
Abnormally low resting RSA or large reductions in RSA specifically during emotion evocation are associated with symptoms of both internalizing and externalizing psychopathology

supported by medial prefrontal cortex to the PNS(inhibitory efferent pathways), RSA measured during executive function task

Emotions are generated by phylogenetically old, subcortical neural circuits but regulatted by phylogenetically new cortical neural circuits

It is far more likely that the PNS via the vagus nerve, mediates links between the PFC and cardiovascular function

Polyvagal Theory leads toward a hierarchical conceptualization
of feelings as higher brain interpretations of the neural signals
conveying information regarding visceral organs (e.g., heart,
gut, etc.) to the brainstem (Porges , 2022)

This psychophysiological perspective
emphasizes the foundational function of autonomic state in the
subjective experiences of global feelings and specific emotions.
Within this hierarchical conceptualization, feelings of safety are preeminent and form the core of an enduring motivational
system that shifts autonomic state, which in turn drives behaviors,
emotions, and thoughts.

The main point of the model is that higher behavioral
functions, which are frequently intentional, are dependent on the
functioning of the more survival focused foundational systems
embedded in the brainstem. 

## References

Beauchaine T. P. (2015). Respiratory Sinus Arrhythmia: A Transdiagnostic Biomarker of Emotion Dysregulation and Psychopathology. Current opinion in psychology, 3, 43–47. https://doi.org/10.1016/j.copsyc.2015.01.017

Porges, S. W. (2022) Polyvagal Theory: A Science of Safety. Front. Integr. Neurosci. 16:871227. doi; 10.3389/fnint.2022.871227

Raine, A., Choy, O., Achenbach, T. et al. (2023) High resting heart rate protects against the intergenerational transmission of antisocial behavior: a birth cohort study. Eur Child Adolesc Psychiatry. https://doi-org.brooklyn.ezproxy.cuny.edu/10.1007/s00787-023-02247-z

Styske, B. , Shaikh, A. I. (2017) A systematic review and meta analysis of the intergeneratioal transmission of criminal behavior


