---
title: "cm_report"
output: pdf_document
author: cmiller
---


## printing some graphs

```{r, echo=FALSE, message=FALSE, include=FALSE}

library(tidyverse)
library(dplyr)
library(ggthemes)
library(readxl)





#disco_hw <- read_xlsx("table_mean_diffs.xlsx")


```

```{r}

scores_and_vitals <- read_xlsx("Discontinuity Measures and Z scores.xlsx")



#glimpse(scores_and_vitals)
#view(scores_and_vitals)


```

```{r}

 
drop_na(scores_and_vitals)%>%
ggplot(scores_and_vitals, mapping = aes( `Aggression Groups`, `Heart Rate`, fill= `Aggression Groups`))+
  
  geom_boxplot(outlier.size=1.5)+
  stat_summary(fun = "mean", geom = "point", shape= 18, size = 2)+
   labs(
    xlab="Four Aggression Groups",
    ylab="Resting Heart Rate",
    title = "Resting Heart Rate in Four Aggression Groups")+
  
  scale_y_continuous(limits = c(55, 130),
                     breaks = seq(55, 130, by=5))+
   
   theme( axis.line = element_line(colour = "dodgerblue", 
                      size = 1, linetype = "solid"))+
  scale_fill_manual(values = c("red", "blue", "gold", "white"))+
 theme_classic()
   
   


```

```{r fig.align="center", echo = FALSE,fig.width = 8}
drop_na(scores_and_vitals)%>%
ggplot(scores_and_vitals, mapping = aes(`Heart Rate`,`Dimensional Score`, fill= `Aggression Groups`))+
  
  geom_point(shape=22, size=3)+
   labs(
    xlab="Heart Rate for Children",
    ylab="Dimensional Discontinuity Score",
    title = "Resting Heart Rate and Dimensional Discontinuity Score")+
    scale_y_continuous(limits = c(-5, 5),
                     breaks = seq(-5, 5, by=0.5))+
  scale_x_continuous(limits = c(55, 130),
                     breaks = seq(55, 130, by=5))+
   
   theme( axis.line = element_line(colour = "blue", 
                      size = 1, linetype = "solid"))+
    geom_hline(yintercept = 0, linetype = "dotdash", color = "blue") 

#?geom_boxplot

   
```

```{r fig.align="center", echo = FALSE,fig.width = 7 }

#scores_and_vitals%>%
 # filter(scores_and_vitals$`Dimensional Score` != "NA")%>%
drop_na(scores_and_vitals)%>%
ggplot(scores_and_vitals, mapping = aes(x=`Heart Rate`, y= `Dimensional Score`, fill = `Aggression Groups`))+
  
  geom_point(shape=21, size=3 )+
  #scale_fill_manual(breaks = c("Both Aggressive", "Child Aggressive", "Neither", "Parent"),
  scale_fill_manual(values = c("red", "blue", "gold", "grey"))+
  #geom_rug(sides="l" )+
  


#  scale_fill_manual(values = c("red", "blue", "yellow", "grey"))+
 # geom_smooth(method= lm, se = FALSE)+
  
 
  
  #geom_smooth(linetype= "dotdash")+
  scale_y_continuous(n.breaks = 25)+
  #geom_density2d()+
 # geom_smooth(method = lm, se = FALSE)+
  #scale_y_continuous(limits = c(-5, 5))
    #                 breaks = seq(-5, 5, by=0.5)
   #                  expand = expand_scale(mult = c(0, 0.5))+
  scale_x_continuous(n.breaks= 20)+
  annotate("text", x = 75, y = 2.3, label.size = 0.1,
    color = "gray17", fill="pink", label = "Parent") +
  annotate("text", x = 70, y = -0.9,  label.size = 0.1,
    color = "red", fill="pink", label = "Both")+
  annotate("text", x = 85, y = -2.0, label.size = 0.1,
    color = "blue", fill="pink", label = "Child")+
  annotate("text", x = 120, y = 0.7, label.size = 0.1,
    color = "gold3", fill="pink", label = "Neither")+
  
   labs(
  
    title = "Discontinuity Score and Resting Heart Rate in Four Aggression Groups")+
    #scale_y_continuous(limits = c(-5, 5),
                     #breaks = seq(-5, 5, by=0.5))+
  #scale_x_continuous(limits = c(55, 130),
                     #breaks = seq(55, 130, by=5))+
   
  # theme( axis.line = element_line(colour = "blue", 
   #                   size = 1, linetype = "solid"))+
    geom_hline(yintercept = 0, linetype = "dotdash", color = "gray") +
  theme_classic()
  
   
 


```



```{r}


tri_heart_rate <- read_xlsx("tri_hearts.xlsx")

#glimpse(tri_heart_rate)


ggplot(tri_heart_rate, mapping = aes(`Trichotomized Heart Rate`, `Mean Discontinuity Score`, fill= `Trichotomized Heart Rate`))+
  
  geom_point(shape=22, size=7)+
   
  
  #geom_line()+
 # geom_line(aes(`Standard Deviation`, `Mean Discontinuity Score`))+
  labs(
   
    title = "Mean Discontinuity Score for Three Heart Rate Groups")+
    scale_y_continuous(limits = c(-0.5, 0.5),
                     breaks = seq(-0.5, 0.5, by=0.05))+
  geom_hline(yintercept = -.0153, linetype = "1F", size=1, alpha=0.8,  color = "blue")+
  geom_hline(yintercept = 0.1263, linetype = "1F",  alpha=0.8,color = "red")+
  geom_hline(yintercept = -0.1874, linetype = "1F", alpha=0.8,color = "green")+
    theme_classic() 
   
  
##   color = "green", fill="pink", label = "Child")

#View(tri_heart_rate)

    #tibble(tri_heart_rate)
 
```

```{r}



drop_na(scores_and_vitals)%>%
  
ggplot(scores_and_vitals, mapping = aes( `Aggression Groups`, `Dimensional Score`, fill= `Aggression Groups`))+
  
  geom_boxplot(outlier.size=1.5, outlier.color="darkslategray4")+
  stat_summary(fun = "mean", geom = "point", shape= 18, size=2)+
   labs(
    
    title = "Dimensional Discontinuity Scores in Four Aggression Groups")+
  
  scale_y_continuous(limits = c(-5, 5),
                     breaks = seq(-5, 5, by=0.5))+
   
   #theme( axis.line = element_line(colour = "dodgerblue", 
                      #size = 1, linetype = "solid"))+
  scale_fill_manual(values = c("red", "blue", "gold", "white"))+
 theme_classic()



```





```{r}


summary(scores_and_vitals)

drop_na(scores_and_vitals)%>%
#scores_and_vitals %>%
  summarise(Parent_Aggression_STDEV= sd(parent_aggression),
          Child_Aggression_STDEV = sd(child_aggression)
)

```


```{r }


mean_parents = mean(scores_and_vitals$parent_aggression, na.rm = TRUE)

mean_parents

drop_na(scores_and_vitals)%>%
ggplot(scores_and_vitals, mapping=aes (parent_aggression)) +
    geom_histogram(bins=20, fill="dodgerblue", color="lightgreen", alpha=0.8)+
    
    #geom_vline(aes(xintercept= mean(`Parent Z Score` )))
#ggplot(scores_and_vitals, mapping= aes( `Parent Z Score`))+
  #geom_histogram( position="identity", alpha=0.6, fill= "dodgerblue", color="pink")+
  
  scale_x_continuous(n.breaks = 20)+
  geom_vline(xintercept = mean_parents , color = "#dc134c", size=1)+
  scale_y_continuous(n.breaks = 5)+
  labs(
    title = "Histogram of Z Transformed Parent Aggression Scores",
    ylab = " ",
    xlab = " Z Scores "
  )+
  theme_calc()
 # scale_x_continuous(limits = c(-3.0, 3.0))
  #                   breaks = seq(-3.0, 3.0, by=0.25)
 # scale_x_continuous(limits = c(55, 130),
     #                breaks = seq(55, 130, by=5))+
   #
   #theme( axis.line = element_line(colour = "blue", 
    #                  size = 1, linetype = "solid"))
    #geom_hline(yintercept = 0, linetype = "dotdash", color = "blue") 
   


```

```{r}


mean_child = mean(scores_and_vitals$child_aggression , na.rm = TRUE)

mean_child

drop_na(scores_and_vitals)%>%
  
  ggplot(scores_and_vitals, mapping=aes (child_aggression)) +
    geom_histogram(bins=20, fill="lightgreen", color="dodgerblue", alpha=0.8)+
    
    #geom_vline(aes(xintercept= mean(`Parent Z Score` )))
#ggplot(scores_and_vitals, mapping= aes( `Parent Z Score`))+
  #geom_histogram( position="identity", alpha=0.6, fill= "dodgerblue", color="pink")+
  
  scale_x_continuous(n.breaks = 25)+
  geom_vline(xintercept = mean_child , color = "#dc134c", size=1)+
  scale_y_continuous(n.breaks = 5)+
  labs(
    title = "Histogram of Z Transformed Child Aggression Scores",
    ylab = " ",
    xlab = " Z Scores "
  )+
  theme_calc()

```


```