---
title: "Data"
author: "C Miller"

categories: [analysis]
---

## Just looking at a table

```{r, echo=FALSE, message=FALSE, include=FALSE}

library(tidyverse)
library(dplyr)
library(ggthemes)
library(readxl)
library(reshape2)
library(knitr)
library(ggrepel)
library(forcats)


disco_hw <- read_xlsx("table_mean_diffs.xlsx")


```

```{r}


disco_hw

glimpse(disco_hw)



```

```{r fig.align="center", echo = FALSE,fig.width = 8}



ggplot(disco_hw, mapping = aes(Heart_Rate_Group, Mean_Discontinuity_Score,fill= Heart_Rate_Group))+
  
  geom_point( shape=22, size=7)+
  labs(
    xlab="Trichotomized Heart Rate Groups",
    ylab="Mean Discontinuity Score",
    title = "Mean Discontinuity Score for Three Heart Rate Groups")+
    scale_y_continuous(limits = c(-0.5, 0.7),
                     breaks = seq(-0.5, 0.7, by=0.05))+
    theme_igray() +
    #lims(y= c(-1,1))+
    #scale_y_continuous(n.breaks = 15)+
   theme( axis.line = element_line(colour = "blue", 
                      size = 1, linetype = "solid"))+
    geom_hline(yintercept = 0, linetype = "dotdash", color = "blue") +

 geom_label(
    label="Highest 25% Heart Rates", 
    x="high",
    y=0.5,
    label.padding = unit(0.1, "lines"), # Rectangle size around label
    label.size = 0.1,
    color = "black",
    fill="pink"
  )+
   geom_label(
    label="Middle 50% Heart Rates", 
    x="middle",
    y=-0.3,
    label.padding = unit(0.2, "lines"), # Rectangle size around label
    label.size = 0.1,
    color = "black",
    fill="pink"
  )+
   geom_label(
    label="Lowest 25% Heart Rates", 
    x="low",
    y=-0.2,
    label.padding = unit(0.2, "lines"), # Rectangle size around label
    label.size = 0.1,
    color = "black",
    fill="pink"
  )

```








```{r}

scores_and_vitals <- read_xlsx("Discontinuity Measures and Z scores.xlsx")



glimpse(scores_and_vitals)
view(scores_and_vitals)


```




```{r}
drop_na(scores_and_vitals)%>%
ggplot(scores_and_vitals, mapping = aes( `Aggression Groups`, `Heart Rate`, color= `Aggression Groups`))+
  
  geom_boxplot()+
 
   labs(
    xlab="Four Aggression Groups",
    ylab="Resting Heart Rate",
    title = "Resting Heart Rate in Four Aggression Groups")+
  
  scale_y_continuous(limits = c(55, 130),
                     breaks = seq(55, 130, by=5))+
   
   theme( axis.line = element_line(colour = "dodgerblue", 
                      size = 1, linetype = "solid"))
   
   


```




```{r fig.align="center", echo = FALSE,fig.width = 8}
drop_na(scores_and_vitals)%>%
ggplot(scores_and_vitals, mapping = aes(`Heart Rate`,`Dimensional Score`, fill= `Aggression Groups`))+
  
  geom_point(shape=22, size=3)+
   labs(
    xlab="Heart Rate for Children",
    ylab="Dimensional Discontinuity Score",
    title = "Resting Heart Rate and Dimensional Discontinuity Score")+
    scale_y_continuous(limits = c(-5, 5),
                     breaks = seq(-5, 5, by=0.5))+
  scale_x_continuous(limits = c(55, 130),
                     breaks = seq(55, 130, by=5))+
   
   theme( axis.line = element_line(colour = "blue", 
                      size = 1, linetype = "solid"))+
    geom_hline(yintercept = 0, linetype = "dotdash", color = "blue") 
   
```


```{r fig.align="center", echo = FALSE,fig.width = 10 }
drop_na(scores_and_vitals)%>%
ggplot(scores_and_vitals, mapping = aes(`Heart Rate`, `Dimensional Score`, color= `Aggression Groups`))+
  
  geom_point(shape=18, size=3)+
  geom_rug(sides = "l")+
  #geom_line(linetype= "dotdash")+
  scale_y_continuous(n.breaks = 25)+
  #geom_density2d()+
 # geom_smooth(method = lm, se = FALSE)+
  #scale_y_continuous(limits = c(-5, 5))
    #                 breaks = seq(-5, 5, by=0.5)
   #                  expand = expand_scale(mult = c(0, 0.5))+
  scale_x_continuous(n.breaks= 20)+
  
   labs(
  
    title = "Dimensional Discontinuity Score and Resting Heart Rate in Four Aggression Groups")+
    #scale_y_continuous(limits = c(-5, 5),
                     #breaks = seq(-5, 5, by=0.5))+
  #scale_x_continuous(limits = c(55, 130),
                     #breaks = seq(55, 130, by=5))+
   
   theme( axis.line = element_line(colour = "blue", 
                      size = 1, linetype = "solid"))+
    geom_hline(yintercept = 0, linetype = "dotdash", color = "orange") 
   
 


```


```{r fig.align="center", echo = FALSE,fig.width = 12}


drop_na(scores_and_vitals)%>%
ggplot(scores_and_vitals, mapping = aes(`Heart Rate`, `Dimensional Score`, color= `Aggression Groups`))+
  
  #geom_bar(stat="identity", position="dodge")+
  geom_line( )+
  geom_point()+
   labs(
    title = "Heart Rate and Four Aggression Groups")+
    scale_y_continuous(n.breaks=20)+
    scale_x_continuous(n.breaks= 20)+
   
   theme( axis.line = element_line(colour = "blue", 
                      size = 1, linetype = "solid"))
   


```





```{r fig.align="center", echo = FALSE,fig.width = 8}


drop_na(scores_and_vitals)%>%
ggplot(scores_and_vitals, mapping = aes(`Aggression Groups`, `Dimensional Score`, color= `Aggression Groups`))+
  geom_point()+
  geom_line(shape=2)+
 
   labs(
    
    title = " Versus  in Children for Four Aggression Groups")+
    scale_y_continuous(limits = c(-5, 5),
                     breaks = seq(-5, 5, by=0.5))+
 # scale_y_continuous(limits = c(50, 140),
  #                  breaks = seq(50, 140, by=5))+
  
  theme_calc()
   


```



```{r }


mean_parents = mean(scores_and_vitals$`Parent Z Score`, na.rm = TRUE)

mean_parents

drop_na(scores_and_vitals)%>%
  
  ggplot(scores_and_vitals, mapping=aes (`Parent Z Score`)) +
    geom_histogram(bins=20, fill="dodgerblue", color="lightgreen", alpha=0.8)+
    
    #geom_vline(aes(xintercept= mean(`Parent Z Score` )))
#ggplot(scores_and_vitals, mapping= aes( `Parent Z Score`))+
  #geom_histogram( position="identity", alpha=0.6, fill= "dodgerblue", color="pink")+
  
  scale_x_continuous(n.breaks = 25)+
  geom_vline(xintercept = mean_parents , color = "#dc134c", size=1)+
  scale_y_continuous(n.breaks = 5)+
  labs(
    title = "Histogram of Z Transformed Parent Aggression Scores",
    ylab = " ",
    xlab = " Z Scores "
  )+
  theme_calc()
 # scale_x_continuous(limits = c(-3.0, 3.0))
  #                   breaks = seq(-3.0, 3.0, by=0.25)
 # scale_x_continuous(limits = c(55, 130),
     #                breaks = seq(55, 130, by=5))+
   #
   #theme( axis.line = element_line(colour = "blue", 
    #                  size = 1, linetype = "solid"))
    #geom_hline(yintercept = 0, linetype = "dotdash", color = "blue") 
   


```



```{r}


mean_child = mean(scores_and_vitals$`Child Z Score`, na.rm = TRUE)

mean_child

drop_na(scores_and_vitals)%>%
  
  ggplot(scores_and_vitals, mapping=aes (`Child Z Score`)) +
    geom_histogram(bins=20, fill="lightgreen", color="dodgerblue", alpha=0.8)+
    
    #geom_vline(aes(xintercept= mean(`Parent Z Score` )))
#ggplot(scores_and_vitals, mapping= aes( `Parent Z Score`))+
  #geom_histogram( position="identity", alpha=0.6, fill= "dodgerblue", color="pink")+
  
  scale_x_continuous(n.breaks = 25)+
  geom_vline(xintercept = mean_child , color = "#dc134c", size=1)+
  scale_y_continuous(n.breaks = 5)+
  labs(
    title = "Histogram of Z Transformed Child Aggression Scores",
    ylab = " ",
    xlab = " Z Scores "
  )+
  theme_calc()

```








```{r fig.align="center", echo = FALSE,fig.width = 12}


drop_na(scores_and_vitals)%>%
ggplot(scores_and_vitals, mapping = aes(`Heart Rate`, `Dimensional Score`, color= `Aggression Groups`))+
  geom_point(shape=17, size=2)+
  geom_line(linetype="longdash")+
 
   labs(
    xlab="Heart Rate in Children",
    ylab="Dimensional Discontinuity Score",
    title = "Dimensional Discontinuity Score Versus Heart Rate in Children for Four Aggression Groups")+
    scale_y_continuous(limits = c(-5, 5),
                     breaks = seq(-5, 5, by=0.5))+
  scale_x_continuous(limits = c(50, 140),
                    breaks = seq(50, 140, by=5))+
  
  theme_calc()
   


```




```{r fig.align="center", echo = FALSE,fig.width = 8 }


drop_na(scores_and_vitals)%>%
ggplot(scores_and_vitals, mapping = aes( `Quintile Heart Rate Group`, `Heart Rate`, fill = `Aggression Groups` ))+
  
  geom_bar(stat="identity", position = "dodge")
 
   labs(
    xlab="Four Aggression Groups",
    ylab="Heart Rate",
    title = "Heart Rate and Four Aggression Groups")+
    scale_y_continuous(limits = c(55, 130),
                     breaks = seq(55, 130, by=5))
    #scale_x_continuous(n.breaks=20)+
   
   theme( axis.line = element_line(colour = "blue", 
                      size = 1, linetype = "solid"))
   


```