---
title: " Slideshow: Special Topics in Psychology: Stressor Tasks and the Autonomic Nervous System  "
format:
  revealjs:
    incremental: true
    theme: [default, style.scss]
    transition: zoom
editor: visual
execute:
  echo: false
---

## Jump Pack to Home

Use the link below or in the bottom left to navigate to the main page

[Link to Website Home](https://miller-c-r.github.io/cm_nsf_reu_didactics/)

## A Presentation by:

C. Miller

CUNY Brooklyn College REU 2024 cohort Senior and Psychology Major

## The Article


**The Article:**

. . .

Correlation of sympathetic and parasympathetic nervous system activity during rest and acute stress tasks

Weissman, D. G., & Mendes, W. B. (2021)

[Article on the web](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7987796/)

## Background

By characterizing the nature of correlated PNS and SNS responses and how these differ based on sex, age, and race, we can better understand how stress responses are coordinated across the autonomic nervous system

Paving the way for a better understanding of individual differences in emotion functioning and mental, and physical health.

## Background

One study took just such an approach in a sample of children who watched emotion-eliciting film clips. On average, RSA and PEP demonstrated coordinated reciprocal activity across baseline and emotion inductions, (Gatzke- Kopp & Ram

,...Further, within and across emotion contexts, the most common form of cross-system autonomic activity is reciprocal. However, the nature and magnitude of RSA-PEP correlations vary between emotion contexts

## Key Terms

-   The Trier Social Stress Task (TSST)

. . .

```         
-   A laboratory stressor designed to characterize an individual's typical response to an acute social stressor in daily life
-   The TSST has well documented effectiveness at inducing psychological distress and physiological stress responses including activation of the hypothalamic pituitary adrenal cortical axis (HPA)
-   Traditionally, the TSST involves the participant planning and delivering a short speech to stoic evaluators, followed by a mental arithmetic task, then, in some cases, a recovery period.
```

## Key Terms

Measures of the SNS

. . .

-   PEP Pre-ejection period (PEP)

    -   A measure of the time between the electrical impulses that initiate ventricle contraction and the opening of the aortic valve, which is primarily influenced by the SNS.

    -   Decreases in PEP indicate an increase in SNS activity

-   Measures of the PNS

    -   RSA

        -   Respiratory sinus arrhythmia (RSA) is high frequency heart rate variability in the respiratory frequency band that reliably estimates PNS control of the heart via the vagus nerve

        -   Respiratory sinus arrhythmia (RSA) is heart rate variability in synchrony with respiration, by which the R-R interval on an ECG is shortened during inspiration and prolonged during expiration (Yasuma, F., & Hayano, J. 2004).

        -   Although RSA has been used as an index of cardiac vagal function, it is also a physiologic phenomenon reflecting respiratory-circulatory interactions universally observed among vertebrates.

## Question

Broad Question

. . .

The myriad social and cognitive challenges faced by humans require flexible modulation of ANS activity for different contexts.

## Question

Specific Question

-   The concurrent relation between RSA and PEP responses was modeled in order to determine the extent to which SNS and PNS activity is correlated across the task within and between participants

-   whether this correlation was moderated by:

    -   age Race sex

    -   baseline RSA and PEP

## Methods

-   Samples combined four previous studies (N=325, 63% female, aged 15-55) in which RSA and PEP were collected continuously during a resting baseline and an acute stressor, the Trier Social Stress Task.

-   This study included 68 black and 73 white participants, 79 female and 62 male participants. Mean age was 29.0 (SD = 10.7, Range 15 to 55)

-   For all four studies, the TSST consisted of a 5-minute baseline, either a 3- or 5-minute speech preparation, followed by a 7- or 5-minute speech, and ending with a 5-minute recovery period.

-   In all studies, participants remained seated for all task periods and were instructed to refrain from **postural changes**.

## Analysis

-   Baseline RSA and PEP were calculated by taking the **mean** of the ***five*** baseline/resting bins.

-   RSA reactivity (ΔRSA) and PEP reactivity (ΔPEP) within each of the task periods were calculated by **subtracting** baseline RSA and PEP from unstandardized RSA and PEP.

-   Differences in the magnitude of ΔRSA and ΔPEP during each task period based on sex and race, and correlations with resting RSA and PEP, age, and with the other indicator during the same task period were calculated.

## Results

-   On average, as expected during active stress tasks, participants' RSA was significantly lower than resting during preparation, speech, math, and Q&A

-   And consistent with vagal rebound, during recovery RSA was significantly higher than resting RSA.

-   Again, consistent with what is expected from active stress tasks, PEP was significantly shorter than resting during preparation, speech, math, and Q&A

-   During recovery PEP was also shorter than resting values consistent with stress residue that can occur immediately after a stressor is complete

-   Overall, RSA and PEP were reciprocally coupled.

-   However, recovery from a stressor was characterized by coactivation.

-   Individuals with higher baseline RSA had greater decreases in RSA relative to baseline across all the task periods

-   Individuals with longer PEP at baseline had greater decreases in PEP during the prep, speech, and math task periods but not during Q&A or recovery

-   Individuals also vary in the extent to which their SNS and PNS are reciprocally coupled:

    -   women, younger adults, and individuals with higher baseline RSA showed more reciprocal coupling than men, older adults, and those with lower baseline RSA, respectively, reflecting **greater coordination of physiological responding in the former group**. \[men and older adults had less reciprocal coupling\]

## Inferences

Overall, the SNS and PNS respond inversely to stress and are reciprocally coupled, perhaps reflecting shared regulatory mechanisms in higher order brain structures and reciprocal responses to environmental demands. H

However, recovery from a stressor is characterized by coactivation on average as the SNS recovers slowly, while PNS activity rebounds and augments to accelerate recovery. Individuals also vary in the extent to which their SNS and PNS are reciprocally coupled

## Limitations

Sample size, methods

Measures of stress

## REFERENCES {.scrollable}

Weissman, D. G., & Mendes, W. B. (2021). Correlation of sympathetic and parasympathetic nervous system activity during rest and acute stress tasks. International journal of psychophysiology : official journal of the International Organization of Psychophysiology, 162, 60--68. https://doi.org/10.1016/j.ijpsycho.2021.01.015

Yasuma, F., & Hayano, J. (2004). Respiratory sinus arrhythmia: why does the heartbeat synchronize with respiratory rhythm?. Chest, 125(2), 683--690. https://doi.org/10.1378/chest.125.2.683
